version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-tcc
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/root/.kube
      - ~/.aws:/root/.aws
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - tcc-network
volumes:
  jenkins_home:
networks:
  tcc-network:
    driver: bridge