pipeline {
    agent any
    environment {
        // Remova a linha do KUBECONFIG antigo, o plugin cuidará disso
        NAMESPACE = 'tcc-jenkins'
    }
    stages {
        stage('Validar e Deploy') {
            steps {
                // O withKubeConfig deve envolver os comandos que precisam de acesso ao cluster
                withKubeConfig([credentialsId: 'k8s-config']) {
                    
                    sh 'kubectl apply --dry-run=client -f k8s-manifests/ -n ${NAMESPACE}'
                    
                    sh 'kubectl apply -f k8s-manifests/deployment.yaml -n ${NAMESPACE}'
                    sh 'kubectl apply -f k8s-manifests/service.yaml -n ${NAMESPACE}'
                    
                    sh 'kubectl apply -f k8s-manifests/hpa.yaml -n ${NAMESPACE}'
                    
                    sh 'kubectl get hpa -n ${NAMESPACE} -o wide'
                }
            }
        }
    }
    post { 
        always { 
            // Aqui também precisa da credencial para não dar erro no final!
            withKubeConfig([credentialsId: 'k8s-config']) {
                sh 'kubectl describe hpa -n ${NAMESPACE}' 
            }
        } 
    }
}