apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-teste-hpa
  namespace: tcc-jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-teste
  template:
    metadata:
      labels:
        app: app-teste
    spec:
      containers:
      - name: app
        image: nginx:latest
        # Comentado para cessar o estresse artificial de CPU após os testes:
        # command: ["/bin/sh", "-c"]
        # args: 
        # - |
        #   (while true; do head -n 10 /dev/urandom | sha256sum; done) & 
        #   nginx -g 'daemon off;'
        resources:
          requests:
            cpu: "5m"
            memory: "32Mi"
          limits:
            cpu: "50m"
            memory: "64Mi"
        ports:
        - containerPort: 80
